# Gradle 配置
org.gradle.jvmargs=-Xmx2G -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7890 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7890
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft 和 NeoForge 版本
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.214
loader_version_range=[4,)

# 模组属性
mod_id=productivebeesgenesis
mod_name=资源蜜蜂：创世
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.ayoshiko
mod_authors=Ayoshiko
mod_description=资源蜜蜂的附属模组，添加了万象创世蜜蜂，可以产出整合包中所有资源蜜蜂的蜜脾。
