package com.ayoshiko.productivebeesgenesis.datagen;

import com.ayoshiko.productivebeesgenesis.ProductiveBeesGenesis;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

/**
 * 语言文件数据生成器
 * <br/>
 * 自动生成配置界面翻译键，保持与 lang/*.json 一致。
 */
public class ModLanguageProvider extends LanguageProvider {

    private final String locale;

    public ModLanguageProvider(PackOutput output, String locale) {
        super(output, ProductiveBeesGenesis.MOD_ID, locale);
        this.locale = locale;
    }

    @Override
    protected void addTranslations() {
        if ("en_us".equals(locale)) {
            addEnglish();
        } else if ("zh_cn".equals(locale)) {
            addChinese();
        }
    }

    private void addEnglish() {
        add("gui.productivebeesgenesis.mek_centrifuge_recipes", "MEK Centrifuge Recipes");
        add("gui.productivebeesgenesis.processing_time", "Time: %dt");
        add("gui.productivebeesgenesis.energy_per_tick", "Energy: %d FE/t");
        add("itemGroup.productivebeesgenesis", "MEK Centrifuge");

        add("productivebeesgenesis.configuration.advanced_beehive", "Advanced Beehive");
        add("productivebeesgenesis.configuration.advanced_beehive.button", "Advanced Beehive");
        add("productivebeesgenesis.configuration.advanced_beehive.tooltip", "Advanced beehive performance optimizations");
        add("productivebeesgenesis.configuration.attack", "Attack");
        add("productivebeesgenesis.configuration.attack.tooltip", "Attack damage");
        add("productivebeesgenesis.configuration.bee_acquisition", "Bee Acquisition");
        add("productivebeesgenesis.configuration.bee_acquisition.button", "Bee Acquisition");
        add("productivebeesgenesis.configuration.bee_acquisition.tooltip", "Myriad Creations bee acquisition methods");
        add("productivebeesgenesis.configuration.bee_attributes", "Bee Attributes");
        add("productivebeesgenesis.configuration.bee_attributes.button", "Bee Attributes");
        add("productivebeesgenesis.configuration.bee_attributes.tooltip", "Myriad Creations Bee Attribute Overrides");
        add("productivebeesgenesis.configuration.bee_conversion", "Bee Conversion");
        add("productivebeesgenesis.configuration.bee_conversion.button", "Bee Conversion");
        add("productivebeesgenesis.configuration.bee_conversion.tooltip", "Convert other bees into Myriad Creations using items");
        add("productivebeesgenesis.configuration.bee_produce", "Bee Produce");
        add("productivebeesgenesis.configuration.bee_produce.button", "Bee Produce");
        add("productivebeesgenesis.configuration.bee_produce.tooltip", "Myriad Creations honeycomb production parameters");
        add("productivebeesgenesis.configuration.behavior", "Behavior");
        add("productivebeesgenesis.configuration.behavior.tooltip", "Behavior: diurnal/nocturnal/metaturnal");
        add("productivebeesgenesis.configuration.biomes", "Biomes");
        add("productivebeesgenesis.configuration.biomes.tooltip", "Biome IDs or tags where this method is active");
        add("productivebeesgenesis.configuration.breeding", "Breeding");
        add("productivebeesgenesis.configuration.breeding.button", "Breeding");
        add("productivebeesgenesis.configuration.breeding.tooltip", "Acquire Myriad Creations bee through breeding");
        add("productivebeesgenesis.configuration.breedingItem", "Breeding Item");
        add("productivebeesgenesis.configuration.breedingItem.tooltip", "Breeding item ID");
        add("productivebeesgenesis.configuration.breedingItemCount", "Breeding Item Count");
        add("productivebeesgenesis.configuration.breedingItemCount.tooltip", "Number of items required for breeding");
        add("productivebeesgenesis.configuration.chance", "Chance");
        add("productivebeesgenesis.configuration.chance.tooltip", "Probability of acquiring the bee (0.0 to 1.0)");
        add("productivebeesgenesis.configuration.colors", "Colors");
        add("productivebeesgenesis.configuration.colors.button", "Colors");
        add("productivebeesgenesis.configuration.colors.tooltip", "Color configuration (written to bee data and rendered on client)");
        add("productivebeesgenesis.configuration.combBlockMultiplier", "Comb Block Output Multiplier");
        add("productivebeesgenesis.configuration.combBlockMultiplier.tooltip", "Multiplier for item and fluid output when centrifuging comb blocks (comb block = N combs)");
        add("productivebeesgenesis.configuration.common", "General");
        add("productivebeesgenesis.configuration.common.button", "General");
        add("productivebeesgenesis.configuration.common.tooltip", "Cross-client synchronized parameters that do not vary by save");
        add("productivebeesgenesis.configuration.devMode", "Developer Mode");
        add("productivebeesgenesis.configuration.devMode.tooltip", "For mod developers only. Enables debug items and config logs not used in normal gameplay. Regular users do not need to enable this.");
        add("productivebeesgenesis.configuration.createComb", "Create Comb");
        add("productivebeesgenesis.configuration.createComb.tooltip", "Whether can produce honeycomb");
        add("productivebeesgenesis.configuration.ejectBusyCooldown", "Busy Eject Cooldown (ticks)");
        add("productivebeesgenesis.configuration.ejectBusyCooldown.tooltip", "Ticks to skip outputItems when output ejection is busy but not fully blocked. Default 40 (2s). 0 disables.");
        add("productivebeesgenesis.configuration.ejectBusyThreshold", "Busy Eject Threshold");
        add("productivebeesgenesis.configuration.ejectBusyThreshold.tooltip", "Consecutive outputItems calls that did not reduce total output count before entering long cooldown. Default 5.");
        add("productivebeesgenesis.configuration.ejectDelay", "Eject Delay (ticks)");
        add("productivebeesgenesis.configuration.ejectDelay.tooltip", "Output slot auto-eject delay. Vanilla Mekanism=10 (0.5s). Lower=faster ejection, higher server load. Recommended: 2 (0.1s)");
        add("productivebeesgenesis.configuration.ejectDelayActive", "Active Eject Delay (ticks)");
        add("productivebeesgenesis.configuration.ejectDelayActive.tooltip", "Eject delay when output slots still contain items (active state). Default 1 (0.05s) for high-throughput scenarios. Lower=faster ejection, higher server load.");
        add("productivebeesgenesis.configuration.ejectMaxPerTick", "Max Eject Calls Per Tick");
        add("productivebeesgenesis.configuration.ejectMaxPerTick.tooltip", "Max outputItems calls per tick (0=unlimited). Limits repeated outputItems calls under 256x acceleration. Default 64; skipped in max speed mode.");
        add("productivebeesgenesis.configuration.ejectMaxSpeedMode", "Max Ejection Speed Mode");
        add("productivebeesgenesis.configuration.ejectMaxSpeedMode.tooltip", "Disables Ejector throttling (skip/interval/busy cooldown) while keeping blocked cooldown, maximizing item ejection speed. Use only when the target container has ample space and server headroom.");
        add("productivebeesgenesis.configuration.ejectMinInterval", "Ejector Min Interval (ticks)");
        add("productivebeesgenesis.configuration.ejectMinInterval.tooltip", "Minimum tick interval between outputItems calls when output slots keep changing. Default 0 (disabled).");
        add("productivebeesgenesis.configuration.ejectSkipTicks", "Ejector Skip Ticks");
        add("productivebeesgenesis.configuration.ejectSkipTicks.tooltip", "Consecutive ticks to skip ejector output attempts when output slots are unchanged. 0 = never skip. Default 1.");
        add("productivebeesgenesis.configuration.ejectSkipUnchanged", "Skip Ejector When Unchanged");
        add("productivebeesgenesis.configuration.ejectSkipUnchanged.tooltip", "Skip ejector output attempts when output slots have not changed, reducing CPU cost under high acceleration.");
        add("productivebeesgenesis.configuration.enablePerformanceMonitor", "Performance Monitor");
        add("productivebeesgenesis.configuration.enablePerformanceMonitor.tooltip", "Enable performance monitoring (Spark compatible, JMX exposed)");
        add("productivebeesgenesis.configuration.enabled", "Enabled");
        add("productivebeesgenesis.configuration.enabled.tooltip", "Enable this acquisition method");
        add("productivebeesgenesis.configuration.endurance", "Endurance");
        add("productivebeesgenesis.configuration.endurance.tooltip", "Endurance: weak/normal/medium/strong");
        add("productivebeesgenesis.configuration.energyPerTick", "Energy Per Tick");
        add("productivebeesgenesis.configuration.energyPerTick.tooltip", "Energy consumption per tick per process (FE)");
        add("productivebeesgenesis.configuration.filterMode", "Filter Mode");
        add("productivebeesgenesis.configuration.filterMode.tooltip", "DISABLED-No filter / BLACKLIST-Exclude listed bee types / WHITELIST-Only allow listed bee types");
        add("productivebeesgenesis.configuration.filteredBeeTypes", "Filtered Bee Types");
        add("productivebeesgenesis.configuration.filteredBeeTypes.tooltip", "Format: modID:beeType, e.g. productivebees:iron");
        add("productivebeesgenesis.configuration.fireproof", "Fireproof");
        add("productivebeesgenesis.configuration.fireproof.tooltip", "Whether fireproof");
        add("productivebeesgenesis.configuration.fishing", "Fishing");
        add("productivebeesgenesis.configuration.fishing.button", "Fishing");
        add("productivebeesgenesis.configuration.fishing.tooltip", "Acquire Myriad Creations bee through fishing");
        add("productivebeesgenesis.configuration.flowerItem", "Flower Item");
        add("productivebeesgenesis.configuration.flowerItem.tooltip", "Pollination item ID");
        add("productivebeesgenesis.configuration.fluidTankCapacity", "Fluid Tank Capacity");
        add("productivebeesgenesis.configuration.fluidTankCapacity.tooltip", "Base fluid output tank capacity (mB), factory version multiplies by process count. Default: 256000 (256 buckets).");
        add("productivebeesgenesis.configuration.glowColor", "Glow Color");
        add("productivebeesgenesis.configuration.glowColor.tooltip", "Glow color (hex format)");
        add("productivebeesgenesis.configuration.glowEnabled", "Glow Effect");
        add("productivebeesgenesis.configuration.glowEnabled.tooltip", "Enable glow effect");
        add("productivebeesgenesis.configuration.item", "Conversion Item");
        add("productivebeesgenesis.configuration.item.tooltip", "Item ID required for conversion (e.g. minecraft:stick)");
        add("productivebeesgenesis.configuration.mekCentrifugeEjectBlockedCooldown", "Blocked Eject Cooldown (ticks)");
        add("productivebeesgenesis.configuration.mekCentrifugeEjectBlockedCooldown.tooltip", "Ticks to skip outputItems when output is blocked. Default 15 (0.75s). 0 disables cooldown.");
        add("productivebeesgenesis.configuration.mekCentrifugeEjectBlockedThreshold", "Blocked Eject Threshold");
        add("productivebeesgenesis.configuration.mekCentrifugeEjectBlockedThreshold.tooltip", "Consecutive failed outputItems attempts before entering cooldown. Default 3.");
        add("productivebeesgenesis.configuration.mekCentrifugeFluidEjectRate", "Fluid Eject Rate (mB/tick)");
        add("productivebeesgenesis.configuration.mekCentrifugeFluidEjectRate.tooltip", "Rate at which fluid is auto-ejected from MEK centrifuges. Default 16384 mB/tick, overrides Mekanism default 1024.");
        add("productivebeesgenesis.configuration.mekCentrifugeMaxExtractPerTick", "Max Extract Per Tick");
        add("productivebeesgenesis.configuration.mekCentrifugeMaxExtractPerTick.tooltip", "Max items extractable per game tick via pipes/AE2 (0=unlimited). Prevents ME interface overload.");
        add("productivebeesgenesis.configuration.mek_centrifuge", "MEK Centrifuge");
        add("productivebeesgenesis.configuration.mek_centrifuge.button", "MEK Centrifuge");
        add("productivebeesgenesis.configuration.mek_centrifuge.tooltip", "MEK Centrifuge settings");
        add("productivebeesgenesis.configuration.mek_port_visualization", "Port Visualization");
        add("productivebeesgenesis.configuration.mek_port_visualization.button", "Port Visualization");
        add("productivebeesgenesis.configuration.mek_port_visualization.tooltip", "Port color visualization settings");
        add("productivebeesgenesis.configuration.myriadProduceThrottlePerTick", "Myriad Produce Throttle Per Tick");
        add("productivebeesgenesis.configuration.myriadProduceThrottlePerTick.tooltip", "Max produce events per game tick per Myriad bee (0=unlimited). Reduces CPU load in heavily accelerated setups.");
        add("productivebeesgenesis.configuration.myriad_creations_filter", "Myriad Creations Filter");
        add("productivebeesgenesis.configuration.myriad_creations_filter.button", "Myriad Creations Filter");
        add("productivebeesgenesis.configuration.myriad_creations_filter.tooltip", "Myriad Creations honeycomb blacklist/whitelist filter settings");
        add("productivebeesgenesis.configuration.nest", "Nest");
        add("productivebeesgenesis.configuration.nest.tooltip", "Nest block for bee spawning (e.g. productivebees:stone_nest)");
        add("productivebeesgenesis.configuration.outputChance", "Output Chance");
        add("productivebeesgenesis.configuration.outputChance.tooltip", "Output probability (0.0 to 1.0)");
        add("productivebeesgenesis.configuration.outputItem", "Output Item");
        add("productivebeesgenesis.configuration.outputItem.tooltip", "Output item ID (e.g. productivebees:configurable_honeycomb)");
        add("productivebeesgenesis.configuration.outputMax", "Output Max");
        add("productivebeesgenesis.configuration.outputMax.tooltip", "Maximum output count");
        add("productivebeesgenesis.configuration.outputMin", "Output Min");
        add("productivebeesgenesis.configuration.outputMin.tooltip", "Minimum output count");
        add("productivebeesgenesis.configuration.parent1", "Parent 1");
        add("productivebeesgenesis.configuration.parent1.tooltip", "First parent bee type (registry name, e.g. productivebees:myriadcreations)");
        add("productivebeesgenesis.configuration.parent2", "Parent 2");
        add("productivebeesgenesis.configuration.parent2.tooltip", "Second parent bee type (registry name)");
        add("productivebeesgenesis.configuration.particleColor", "Particle Color");
        add("productivebeesgenesis.configuration.particleColor.tooltip", "Particle color");
        add("productivebeesgenesis.configuration.particleCount", "Particle Count");
        add("productivebeesgenesis.configuration.particleCount.tooltip", "Number of particles generated per tick");
        add("productivebeesgenesis.configuration.particleEffectEnabled", "Particle Effects");
        add("productivebeesgenesis.configuration.particleEffectEnabled.tooltip", "Enable rainbow particle effects");
        add("productivebeesgenesis.configuration.pb_attributes", "PB Attributes");
        add("productivebeesgenesis.configuration.pb_attributes.button", "PB Attributes");
        add("productivebeesgenesis.configuration.pb_attributes.tooltip", "Productive Bees Exclusive Attributes");
        add("productivebeesgenesis.configuration.portColorRenderRange", "Port Color Render Range");
        add("productivebeesgenesis.configuration.portColorRenderRange.tooltip", "Range in blocks for port color visualization");
        add("productivebeesgenesis.configuration.primaryColor", "Primary Color");
        add("productivebeesgenesis.configuration.primaryColor.tooltip", "Main color (hex format, e.g. #FFD700)");
        add("productivebeesgenesis.configuration.processingTime", "Processing Time (ticks)");
        add("productivebeesgenesis.configuration.processingTime.tooltip", "Base processing time in ticks per operation");
        add("productivebeesgenesis.configuration.productivity", "Productivity");
        add("productivebeesgenesis.configuration.productivity.tooltip", "Productivity: normal/medium/high/very_high");
        add("productivebeesgenesis.configuration.rainbowMode", "Rainbow Mode");
        add("productivebeesgenesis.configuration.rainbowMode.tooltip", "Enable rainbow mode (colors change dynamically)");
        add("productivebeesgenesis.configuration.rainbow_effects", "Rainbow Effects");
        add("productivebeesgenesis.configuration.rainbow_effects.button", "Rainbow Effects");
        add("productivebeesgenesis.configuration.rainbow_effects.tooltip", "Rainbow particle and glow effects");
        add("productivebeesgenesis.configuration.result", "Result Bee");
        add("productivebeesgenesis.configuration.result.tooltip", "Result bee type (registry name, e.g. productivebees:myriadcreations)");
        add("productivebeesgenesis.configuration.secondaryColor", "Secondary Color");
        add("productivebeesgenesis.configuration.secondaryColor.tooltip", "Secondary color");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.client.toml", "Client Settings");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.client.toml.title", "Client Configuration");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.common.toml", "General Settings");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.common.toml.title", "General Configuration");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.server.toml", "Server Settings");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.server.toml.title", "Server Configuration");
        add("productivebeesgenesis.configuration.selfbreed", "Self Breed");
        add("productivebeesgenesis.configuration.selfbreed.tooltip", "Whether can breed within the same species");
        add("productivebeesgenesis.configuration.server.other", "Other Server Settings");
        add("productivebeesgenesis.configuration.server.other.button", "Other Server Settings");
        add("productivebeesgenesis.configuration.server.other.tooltip", "Server-side parameters such as bee attributes, acquisition, conversion, produce, advanced beehive, and MEK centrifuge");
        add("productivebeesgenesis.configuration.showPortColors", "Show Port Colors");
        add("productivebeesgenesis.configuration.showPortColors.tooltip", "Show port configuration colors on MEK centrifuge blocks when holding a Configurator or Configuration Card");
        add("productivebeesgenesis.configuration.simulateCooldown", "Simulate Query Cooldown (ticks)");
        add("productivebeesgenesis.configuration.simulateCooldown.tooltip", "Cooldown between farmer/hoarder/collector queries in simulateBee(). 0 = no limit (vanilla behavior). Recommended 1-5 under high load.");
        add("productivebeesgenesis.configuration.size", "Size");
        add("productivebeesgenesis.configuration.size.tooltip", "Bee size");
        add("productivebeesgenesis.configuration.source", "Source Bee");
        add("productivebeesgenesis.configuration.source.tooltip", "Source bee type (registry name, e.g. minecraft:bee)");
        add("productivebeesgenesis.configuration.spawning", "Spawning");
        add("productivebeesgenesis.configuration.spawning.button", "Spawning");
        add("productivebeesgenesis.configuration.spawning.tooltip", "Acquire Myriad Creations bee through nest spawning");
        add("productivebeesgenesis.configuration.speed", "Speed");
        add("productivebeesgenesis.configuration.speed.tooltip", "Flight speed");
        add("productivebeesgenesis.configuration.temper", "Temper");
        add("productivebeesgenesis.configuration.temper.tooltip", "Temperament: passive/normal/hostile/aggressive");
        add("productivebeesgenesis.configuration.title", "Productive Bees Genesis Configuration");
        add("productivebeesgenesis.configuration.waterproof", "Waterproof");
        add("productivebeesgenesis.configuration.waterproof.tooltip", "Whether waterproof");
        add("productivebeesgenesis.configuration.weatherTolerance", "Weather Tolerance");
        add("productivebeesgenesis.configuration.weatherTolerance.tooltip", "Weather tolerance: none/rain/any");

        // FilterListScreen 工具按钮提示
        add("productivebeesgenesis.config.reset.tooltip", "Reset filter list to default (empty, mode disabled)");
        add("productivebeesgenesis.config.export.tooltip", "Export current filter list to clipboard as JSON array");
        add("productivebeesgenesis.config.import.tooltip", "Import filter list from clipboard (JSON array or comma/line separated)");
    }

    private void addChinese() {
        add("gui.productivebeesgenesis.mek_centrifuge_recipes", "MEK离心机配方");
        add("gui.productivebeesgenesis.processing_time", "时间: %dt");
        add("gui.productivebeesgenesis.energy_per_tick", "能量: %d FE/t");
        add("itemGroup.productivebeesgenesis", "MEK离心机");

        add("productivebeesgenesis.configuration.advanced_beehive", "高级蜂箱");
        add("productivebeesgenesis.configuration.advanced_beehive.button", "高级蜂箱");
        add("productivebeesgenesis.configuration.advanced_beehive.tooltip", "高级蜂箱性能优化设置");
        add("productivebeesgenesis.configuration.attack", "攻击力");
        add("productivebeesgenesis.configuration.attack.tooltip", "攻击伤害");
        add("productivebeesgenesis.configuration.bee_acquisition", "蜜蜂获得方式");
        add("productivebeesgenesis.configuration.bee_acquisition.button", "蜜蜂获得方式");
        add("productivebeesgenesis.configuration.bee_acquisition.tooltip", "万象创世蜜蜂获得方式配置");
        add("productivebeesgenesis.configuration.bee_attributes", "蜜蜂属性");
        add("productivebeesgenesis.configuration.bee_attributes.button", "蜜蜂属性");
        add("productivebeesgenesis.configuration.bee_attributes.tooltip", "万象创世蜜蜂属性覆盖配置");
        add("productivebeesgenesis.configuration.bee_conversion", "蜜蜂转化");
        add("productivebeesgenesis.configuration.bee_conversion.button", "蜜蜂转化");
        add("productivebeesgenesis.configuration.bee_conversion.tooltip", "用其他物品转化获得万象创世蜜蜂");
        add("productivebeesgenesis.configuration.bee_produce", "蜜蜂产出");
        add("productivebeesgenesis.configuration.bee_produce.button", "蜜蜂产出");
        add("productivebeesgenesis.configuration.bee_produce.tooltip", "万象创世蜜脾产出参数配置");
        add("productivebeesgenesis.configuration.behavior", "行为");
        add("productivebeesgenesis.configuration.behavior.tooltip", "行为: diurnal/nocturnal/metaturnal");
        add("productivebeesgenesis.configuration.biomes", "群系");
        add("productivebeesgenesis.configuration.biomes.tooltip", "此获得方式生效的群系ID或标签");
        add("productivebeesgenesis.configuration.breeding", "繁殖获得");
        add("productivebeesgenesis.configuration.breeding.button", "繁殖获得");
        add("productivebeesgenesis.configuration.breeding.tooltip", "通过繁殖获得万象创世蜜蜂");
        add("productivebeesgenesis.configuration.breedingItem", "繁殖物品");
        add("productivebeesgenesis.configuration.breedingItem.tooltip", "繁殖物品ID");
        add("productivebeesgenesis.configuration.breedingItemCount", "繁殖数量");
        add("productivebeesgenesis.configuration.breedingItemCount.tooltip", "繁殖所需物品数量");
        add("productivebeesgenesis.configuration.chance", "概率");
        add("productivebeesgenesis.configuration.chance.tooltip", "获得蜜蜂的概率（0.0~1.0）");
        add("productivebeesgenesis.configuration.colors", "颜色");
        add("productivebeesgenesis.configuration.colors.button", "颜色");
        add("productivebeesgenesis.configuration.colors.tooltip", "颜色配置（写入蜜蜂数据并在客户端渲染）");
        add("productivebeesgenesis.configuration.combBlockMultiplier", "蜜脾块产出倍率");
        add("productivebeesgenesis.configuration.combBlockMultiplier.tooltip", "离心蜜脾块时物品和流体产出的倍数（蜜脾块 = N个蜜脾）");
        add("productivebeesgenesis.configuration.common", "通用配置");
        add("productivebeesgenesis.configuration.common.button", "通用配置");
        add("productivebeesgenesis.configuration.common.tooltip", "跨端同步且无需按存档区分的参数");
        add("productivebeesgenesis.configuration.devMode", "开发者模式");
        add("productivebeesgenesis.configuration.devMode.tooltip", "模组开发者用来调试模组正常功能不会用到的物品和调试配置日志等，用户无需开启此设置。");
        add("productivebeesgenesis.configuration.createComb", "产出蜜脾");
        add("productivebeesgenesis.configuration.createComb.tooltip", "是否能产出蜜脾");
        add("productivebeesgenesis.configuration.ejectBusyCooldown", "高负载弹出冷却（tick）");
        add("productivebeesgenesis.configuration.ejectBusyCooldown.tooltip", "输出侧高负载但未完全阻塞时跳过 outputItems 的 tick 数。默认40 tick（2秒），0=关闭。");
        add("productivebeesgenesis.configuration.ejectBusyThreshold", "高负载弹出阈值");
        add("productivebeesgenesis.configuration.ejectBusyThreshold.tooltip", "连续多少次 outputItems 未减少输出槽物品总量后进入长冷却。默认5次。");
        add("productivebeesgenesis.configuration.ejectDelay", "弹出延迟（tick）");
        add("productivebeesgenesis.configuration.ejectDelay.tooltip", "输出槽自动弹出延迟。原版Mekanism=10（0.5秒）。值越小弹出越快，服务器负载越高。推荐：2（0.1秒）");
        add("productivebeesgenesis.configuration.ejectDelayActive", "活动弹出延迟（tick）");
        add("productivebeesgenesis.configuration.ejectDelayActive.tooltip", "输出槽仍有物品时（活动状态）的弹出延迟。默认1（0.05秒），适用于高产出场景。值越小弹出越快，服务器负载越高。");
        add("productivebeesgenesis.configuration.ejectMaxPerTick", "单tick最大弹出次数");
        add("productivebeesgenesis.configuration.ejectMaxPerTick.tooltip", "单 tick 内 outputItems 的最大调用次数上限（0=无限制）。限制 256× 加速下单 tick 产生海量物品时反复调用 outputItems。默认 64；最大速度模式下跳过此上限。");
        add("productivebeesgenesis.configuration.ejectMaxSpeedMode", "最大弹出速度模式");
        add("productivebeesgenesis.configuration.ejectMaxSpeedMode.tooltip", "关闭 Ejector 的未变化跳过、最小调用间隔和高负载长冷却等节流逻辑，仅保留阻塞冷却，以最大化物品弹出速度。仅推荐目标容器空间充足且服务器性能冗余时使用。");
        add("productivebeesgenesis.configuration.ejectMinInterval", "弹出最小间隔（tick）");
        add("productivebeesgenesis.configuration.ejectMinInterval.tooltip", "输出槽内容持续变化时，两次 outputItems 调用之间的最小 tick 间隔。默认0（关闭）。");
        add("productivebeesgenesis.configuration.ejectSkipTicks", "输出未变化跳过刻数");
        add("productivebeesgenesis.configuration.ejectSkipTicks.tooltip", "输出槽内容未变化时连续跳过 outputItems 的 tick 数。0 = 不跳过。默认值：1。");
        add("productivebeesgenesis.configuration.ejectSkipUnchanged", "输出未变化时跳过弹出");
        add("productivebeesgenesis.configuration.ejectSkipUnchanged.tooltip", "当输出槽内容未变化时跳过 Ejector 输出尝试，降低高倍加速下的 CPU 开销。");
        add("productivebeesgenesis.configuration.enablePerformanceMonitor", "性能监控");
        add("productivebeesgenesis.configuration.enablePerformanceMonitor.tooltip", "启用性能监控（兼容Spark，通过JMX暴露数据）");
        add("productivebeesgenesis.configuration.enabled", "启用");
        add("productivebeesgenesis.configuration.enabled.tooltip", "启用此获得方式");
        add("productivebeesgenesis.configuration.endurance", "耐力");
        add("productivebeesgenesis.configuration.endurance.tooltip", "耐力: weak/normal/medium/strong");
        add("productivebeesgenesis.configuration.energyPerTick", "每tick能量消耗");
        add("productivebeesgenesis.configuration.energyPerTick.tooltip", "每个处理槽每tick的能量消耗（FE）");
        add("productivebeesgenesis.configuration.filterMode", "过滤模式");
        add("productivebeesgenesis.configuration.filterMode.tooltip", "DISABLED-不过滤 / BLACKLIST-排除列表中的蜜蜂类型 / WHITELIST-仅允许列表中的蜜蜂类型");
        add("productivebeesgenesis.configuration.filteredBeeTypes", "过滤的蜜蜂类型");
        add("productivebeesgenesis.configuration.filteredBeeTypes.tooltip", "格式: 模组ID:蜜蜂类型，如 productivebees:iron");
        add("productivebeesgenesis.configuration.fireproof", "防火");
        add("productivebeesgenesis.configuration.fireproof.tooltip", "是否防火");
        add("productivebeesgenesis.configuration.fishing", "钓鱼获得");
        add("productivebeesgenesis.configuration.fishing.button", "钓鱼获得");
        add("productivebeesgenesis.configuration.fishing.tooltip", "通过钓鱼获得万象创世蜜蜂");
        add("productivebeesgenesis.configuration.flowerItem", "授粉物品");
        add("productivebeesgenesis.configuration.flowerItem.tooltip", "授粉物品ID");
        add("productivebeesgenesis.configuration.fluidTankCapacity", "流体罐容量");
        add("productivebeesgenesis.configuration.fluidTankCapacity.tooltip", "流体输出罐基础容量(mB)，工厂版会按并行数倍增此值。默认值：256000（256桶）。");
        add("productivebeesgenesis.configuration.glowColor", "光晕颜色");
        add("productivebeesgenesis.configuration.glowColor.tooltip", "光晕颜色（十六进制）");
        add("productivebeesgenesis.configuration.glowEnabled", "光晕效果");
        add("productivebeesgenesis.configuration.glowEnabled.tooltip", "启用光晕效果");
        add("productivebeesgenesis.configuration.item", "转化物品");
        add("productivebeesgenesis.configuration.item.tooltip", "转化所需物品ID（如 minecraft:stick）");
        add("productivebeesgenesis.configuration.mekCentrifugeEjectBlockedCooldown", "输出阻塞冷却（tick）");
        add("productivebeesgenesis.configuration.mekCentrifugeEjectBlockedCooldown.tooltip", "输出侧阻塞时跳过 outputItems 的 tick 数。默认15 tick（0.75秒），0=关闭冷却。");
        add("productivebeesgenesis.configuration.mekCentrifugeEjectBlockedThreshold", "输出阻塞阈值");
        add("productivebeesgenesis.configuration.mekCentrifugeEjectBlockedThreshold.tooltip", "连续多少次 outputItems 未弹出物品后进入冷却。默认3次。");
        add("productivebeesgenesis.configuration.mekCentrifugeFluidEjectRate", "流体弹出速率(mB/tick)");
        add("productivebeesgenesis.configuration.mekCentrifugeFluidEjectRate.tooltip", "MEK离心机流体自动弹出速率。默认16384 mB/tick，覆盖Mekanism默认的1024。");
        add("productivebeesgenesis.configuration.mekCentrifugeMaxExtractPerTick", "每刻最大拉取量");
        add("productivebeesgenesis.configuration.mekCentrifugeMaxExtractPerTick.tooltip", "每游戏刻外部通过管道/AE2从离心机输出槽拉取的最大物品总数（0=无限制）。防止ME接口过载拉取导致主线程卡顿。");
        add("productivebeesgenesis.configuration.mek_centrifuge", "MEK离心机");
        add("productivebeesgenesis.configuration.mek_centrifuge.button", "MEK离心机");
        add("productivebeesgenesis.configuration.mek_centrifuge.tooltip", "MEK离心机设置");
        add("productivebeesgenesis.configuration.mek_port_visualization", "端口可视化");
        add("productivebeesgenesis.configuration.mek_port_visualization.button", "端口可视化");
        add("productivebeesgenesis.configuration.mek_port_visualization.tooltip", "端口颜色可视化设置");
        add("productivebeesgenesis.configuration.myriadProduceThrottlePerTick", "万象创世每刻产物节流");
        add("productivebeesgenesis.configuration.myriadProduceThrottlePerTick.tooltip", "每游戏刻每只万象创世蜜蜂的最大产物事件数（0=无限制）。在高倍加速/ME接口高频拉取场景下可降低CPU负载。");
        add("productivebeesgenesis.configuration.myriad_creations_filter", "万象创世过滤");
        add("productivebeesgenesis.configuration.myriad_creations_filter.button", "万象创世过滤");
        add("productivebeesgenesis.configuration.myriad_creations_filter.tooltip", "万象创世蜜脾黑白名单过滤设置");
        add("productivebeesgenesis.configuration.nest", "蜂巢");
        add("productivebeesgenesis.configuration.nest.tooltip", "生成蜜蜂的蜂巢方块（如 productivebees:stone_nest）");
        add("productivebeesgenesis.configuration.outputChance", "产出概率");
        add("productivebeesgenesis.configuration.outputChance.tooltip", "产出概率（0.0~1.0）");
        add("productivebeesgenesis.configuration.outputItem", "产出物品");
        add("productivebeesgenesis.configuration.outputItem.tooltip", "产出物品ID（如 productivebees:configurable_honeycomb）");
        add("productivebeesgenesis.configuration.outputMax", "最大产出");
        add("productivebeesgenesis.configuration.outputMax.tooltip", "最大产出数量");
        add("productivebeesgenesis.configuration.outputMin", "最小产出");
        add("productivebeesgenesis.configuration.outputMin.tooltip", "最小产出数量");
        add("productivebeesgenesis.configuration.parent1", "亲代1");
        add("productivebeesgenesis.configuration.parent1.tooltip", "亲代蜜蜂1（注册名，如 productivebees:myriadcreations）");
        add("productivebeesgenesis.configuration.parent2", "亲代2");
        add("productivebeesgenesis.configuration.parent2.tooltip", "亲代蜜蜂2（注册名）");
        add("productivebeesgenesis.configuration.particleColor", "粒子颜色");
        add("productivebeesgenesis.configuration.particleColor.tooltip", "粒子颜色");
        add("productivebeesgenesis.configuration.particleCount", "粒子数量");
        add("productivebeesgenesis.configuration.particleCount.tooltip", "每个tick生成的粒子数量");
        add("productivebeesgenesis.configuration.particleEffectEnabled", "粒子效果");
        add("productivebeesgenesis.configuration.particleEffectEnabled.tooltip", "启用彩虹粒子特效");
        add("productivebeesgenesis.configuration.pb_attributes", "PB 属性");
        add("productivebeesgenesis.configuration.pb_attributes.button", "PB 属性");
        add("productivebeesgenesis.configuration.pb_attributes.tooltip", "Productive Bees 独有属性");
        add("productivebeesgenesis.configuration.portColorRenderRange", "端口颜色渲染范围");
        add("productivebeesgenesis.configuration.portColorRenderRange.tooltip", "端口颜色可视化的渲染范围（格）");
        add("productivebeesgenesis.configuration.primaryColor", "主颜色");
        add("productivebeesgenesis.configuration.primaryColor.tooltip", "主颜色（十六进制格式，如 #FFD700）");
        add("productivebeesgenesis.configuration.processingTime", "处理时间（tick）");
        add("productivebeesgenesis.configuration.processingTime.tooltip", "每次操作的基础处理时间（tick）");
        add("productivebeesgenesis.configuration.productivity", "产量");
        add("productivebeesgenesis.configuration.productivity.tooltip", "产量: normal/medium/high/very_high");
        add("productivebeesgenesis.configuration.rainbowMode", "彩虹模式");
        add("productivebeesgenesis.configuration.rainbowMode.tooltip", "启用彩虹模式（颜色会动态变化）");
        add("productivebeesgenesis.configuration.rainbow_effects", "彩虹特效");
        add("productivebeesgenesis.configuration.rainbow_effects.button", "彩虹特效");
        add("productivebeesgenesis.configuration.rainbow_effects.tooltip", "彩虹粒子和发光效果");
        add("productivebeesgenesis.configuration.result", "目标蜜蜂");
        add("productivebeesgenesis.configuration.result.tooltip", "转化目标蜜蜂（注册名，如 productivebees:myriadcreations）");
        add("productivebeesgenesis.configuration.secondaryColor", "次要颜色");
        add("productivebeesgenesis.configuration.secondaryColor.tooltip", "次要颜色");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.client.toml", "客户端设置");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.client.toml.title", "客户端配置");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.common.toml", "通用设置");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.common.toml.title", "通用配置");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.server.toml", "服务端设置");
        add("productivebeesgenesis.configuration.section.productivebeesgenesis.server.toml.title", "服务端配置");
        add("productivebeesgenesis.configuration.selfbreed", "种内繁殖");
        add("productivebeesgenesis.configuration.selfbreed.tooltip", "是否可种内繁殖");
        add("productivebeesgenesis.configuration.server.other", "其他服务端配置");
        add("productivebeesgenesis.configuration.server.other.button", "其他服务端配置");
        add("productivebeesgenesis.configuration.server.other.tooltip", "蜜蜂属性、获得方式、转化产出、高级蜂箱、MEK离心机等服务端参数");
        add("productivebeesgenesis.configuration.showPortColors", "显示端口颜色");
        add("productivebeesgenesis.configuration.showPortColors.tooltip", "手持Mekanism配置器或配置卡时在MEK离心机方块上显示端口配置颜色");
        add("productivebeesgenesis.configuration.simulateCooldown", "模拟查询冷却（tick）");
        add("productivebeesgenesis.configuration.simulateCooldown.tooltip", "simulateBee() 中农夫/囤积/收集行为扫描附近作物或掉落物的冷却。0=不限制（原版行为），高负载场景建议 1-5。");
        add("productivebeesgenesis.configuration.size", "大小");
        add("productivebeesgenesis.configuration.size.tooltip", "蜜蜂大小");
        add("productivebeesgenesis.configuration.source", "源蜜蜂");
        add("productivebeesgenesis.configuration.source.tooltip", "源蜜蜂类型（注册名，如 minecraft:bee）");
        add("productivebeesgenesis.configuration.spawning", "蜂巢生成");
        add("productivebeesgenesis.configuration.spawning.button", "蜂巢生成");
        add("productivebeesgenesis.configuration.spawning.tooltip", "通过蜂巢自然生成万象创世蜜蜂");
        add("productivebeesgenesis.configuration.speed", "速度");
        add("productivebeesgenesis.configuration.speed.tooltip", "飞行速度");
        add("productivebeesgenesis.configuration.temper", "性格");
        add("productivebeesgenesis.configuration.temper.tooltip", "性格: passive/normal/hostile/aggressive");
        add("productivebeesgenesis.configuration.title", "资源蜜蜂：创世配置");
        add("productivebeesgenesis.configuration.waterproof", "防水");
        add("productivebeesgenesis.configuration.waterproof.tooltip", "是否防水");
        add("productivebeesgenesis.configuration.weatherTolerance", "天气耐受性");
        add("productivebeesgenesis.configuration.weatherTolerance.tooltip", "天气耐受性: none/rain/any");

        // FilterListScreen 工具按钮提示
        add("productivebeesgenesis.config.reset.tooltip", "重置过滤列表为默认值（空列表、模式关闭）");
        add("productivebeesgenesis.config.export.tooltip", "将当前过滤列表以 JSON 数组形式导出到剪贴板");
        add("productivebeesgenesis.config.import.tooltip", "从剪贴板导入过滤列表（支持 JSON 数组或逗号/换行分隔）");
    }
}
